title: Just a Blog
markdown: kramdown
highlighter: rouge

# SEO & Site Configuration
url: "https://see-quick.github.io"
baseurl: ""
description: "Technical blog about formal verification, Kubernetes, DevOps, Apache Kafka, and distributed systems. Practical guides and deep dives into software engineering."
lang: en_US

kramdown:
  input: GFM
  syntax_highlighter: rouge

# for atom feed
author:
  name: Maros Orsak
  email: maros.orsak159@gmail.com

# Social profiles for SEO
twitter:
  username: see_quick
  card: summary_large_image

social:
  name: Maros Orsak
  links:
    - https://github.com/see-quick

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

paginate: 6 # This is the number of posts you want to show per page
paginate_path: "/page:num/" # This is the URL structure for the paginated pages