{
 "title": "Strimzi Operators",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "2024-02-25T12:36:25.370Z", "to": "2024-02-25T12:42:54.787Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Topic Reconciliation Heatmap",
   "type": "heatmap",
   "description": "The heatmap shows different time intervals on the x-axis, with the duration buckets on the y-axis. Each cell in the heatmap has a color that represents the number of reconciliations that fell into the corresponding duration bucket during that time interval. Darker or brighter colors typically indicate higher frequencies of reconciliations in that duration range.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(strimzi_reconciliations_duration_seconds_bucket{kind=\"KafkaTopic\"}[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview and Capacity Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Kafka CRs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Topics CRs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaTopic\"})"
    }
   ]
  },
  {
   "title": "Maximum Queue Size",
   "type": "stat",
   "description": "Monitors the maximum size of the operator's queue to ensure it's not being overloaded.",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(strimzi_reconciliations_max_queue_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum size of single-event batch",
   "type": "stat",
   "description": "Max size recorded for single-event batch",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(strimzi_reconciliations_max_batch_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Operator Tasks - Peak Duration Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Topic Config Alteration - Max Duration",
   "type": "timeseries",
   "description": "Alter configs seconds",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "strimzi_alter_configs_duration_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Creation - Max Duration",
   "type": "timeseries",
   "description": "Shows the longest time taken to create a topic, highlighting potential performance bottlenecks.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "strimzi_create_topics_duration_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Status Update - Max Duration",
   "type": "timeseries",
   "description": "The time the updateStatus Kubernetes operation takes to complete",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "strimzi_update_status_duration_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Config Query - Max Duration",
   "type": "timeseries",
   "description": "The time the describeConfigs Kafka operation takes to complete",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "strimzi_describe_configs_duration_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Average Create Topics Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "strimzi_create_topics_duration_seconds_sum{container=~\"topic-operator\"}/strimzi_create_topics_duration_seconds_count{container=~\"topic-operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Create Partitions Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "strimzi_create_partitions_duration_seconds_sum/strimzi_create_partitions_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Reconciliations Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "strimzi_reconciliations_duration_seconds_sum{container=~\"topic-operator\"}/strimzi_reconciliations_duration_seconds_count{container=~\"topic-operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Describe Topics Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "strimzi_describe_topics_duration_seconds_sum/strimzi_describe_topics_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Alter Configs Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "strimzi_alter_configs_duration_seconds_sum/strimzi_alter_configs_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Update Status Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "strimzi_update_status_duration_seconds_sum/strimzi_update_status_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Describe Configs Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "strimzi_describe_configs_duration_seconds_sum/strimzi_describe_configs_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Delete Topics Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "strimzi_delete_topics_duration_seconds_sum/strimzi_delete_topics_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful Reconciliation per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_successful_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Failed Reconciliation per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Reconciliation without Lock per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_locked_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Started Reconciliation per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Periodical Reconciliation per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_periodical_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Maximum reconciliation time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_reconciliations_duration_seconds_max) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=~\"user-operator|topic-operator|strimzi-cluster-operator\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{container=~\"user-operator|topic-operator|strimzi-cluster-operator\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{container=~\"user-operator|topic-operator|strimzi-cluster-operator\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}